security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: mail
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            jwt: ~
        admin:
            lazy: true
            provider: app_user_provider
            pattern: ^/admin
            logout:
                path: app_logout
                target: app_login
            custom_authenticator:
                - App\Security\AppAuthenticator
        main:
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/me, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/doc.json, roles: ROLE_ADMIN }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - {
              path: ^/api/properties,
              roles: IS_AUTHENTICATED_FULLY,
              methods: [POST, PUT, DELETE],
          }
        - { path: ^/api/properties, roles: PUBLIC_ACCESS, methods: [GET] }
        - {
              path: ^/api/images,
              roles: IS_AUTHENTICATED_FULLY,
              methods: [POST, PUT, DELETE],
          }
        - { path: ^/api/images, roles: PUBLIC_ACCESS, methods: [GET] }
        - {
              path: ^/api/income_frequencies,
              roles: IS_AUTHENTICATED_FULLY,
              methods: [POST, PUT, DELETE],
          }
        - {
              path: ^/api/income_frequencies,
              roles: PUBLIC_ACCESS,
              methods: [GET],
          }
        - {
              path: ^/api/roles,
              roles: IS_AUTHENTICATED_FULLY,
              methods: [GET, POST, PUT, DELETE],
          }
        - { path: ^/api/securitytokens, roles: PUBLIC_ACCESS, methods: [GET] }
        - {
              path: ^/api/securitytokens,
              roles: IS_AUTHENTICATED_FULLY,
              methods: [POST, PUT, DELETE],
          }
        - {
              path: ^/api/securitytokenwallets,
              roles: IS_AUTHENTICATED_FULLY,
              methods: [GET, POST, PUT, DELETE],
          }
        - {
              path: ^/api/securitytokenwallets,
              roles: IS_AUTHENTICATED_FULLY,
              methods: [POST],
          }
        - {
              path: ^/api/types,
              roles: IS_AUTHENTICATED_FULLY,
              methods: [POST, PUT, DELETE],
          }
        - { path: ^/api/types, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/users, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/usersbytoken, roles: PUBLIC_ACCESS, methods: [GET] }
        - {
              path: ^/api/users,
              roles: IS_AUTHENTICATED_FULLY,
              methods: [GET, PUT, DELETE],
          }
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
